---
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-vet
      - id: go-build
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: test
        name: Running Go Tests
        entry: go test ./internal/pulse
        language: golang
        pass_filenames: false
