---
    name: Go Tests
    
    on:
      pull_request:
        types: [opened, synchronize]
    
    permissions:
      contents: read
    
    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v5
    
          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: 1.25.0
    
          - name: Run go test
            run: |
              go test ./internal/pulse
